/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AttemptRouteImport } from './routes/attempt'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ResultRouteImport } from './routes/result'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCreateRouteImport } from './routes/admin.create'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLeaderboardRouteImport } from './routes/admin.leaderboard'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AttemptAttemptIdRouteImport } from './routes/attempt_.$attemptId'
import { Route as QuizOfflineCheckRouteImport } from './routes/quiz.offline-check'
import { Route as QuizPrepareRouteImport } from './routes/quiz.prepare'
import { Route as ApiPublicConnectivityCheckRouteImport } from './routes/api/public/connectivity-check'
import { Route as ApiPublicSubmitAttemptRouteImport } from './routes/api/public/submit-attempt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptRoute = AttemptRouteImport.update({
  id: '/attempt',
  path: '/attempt',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AttemptAttemptIdRoute = AttemptAttemptIdRouteImport.update({
  id: '/attempt_/$attemptId',
  path: '/attempt/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizOfflineCheckRoute = QuizOfflineCheckRouteImport.update({
  id: '/quiz/offline-check',
  path: '/quiz/offline-check',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizPrepareRoute = QuizPrepareRouteImport.update({
  id: '/quiz/prepare',
  path: '/quiz/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConnectivityCheckRoute =
  ApiPublicConnectivityCheckRouteImport.update({
    id: '/api/public/connectivity-check',
    path: '/api/public/connectivity-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSubmitAttemptRoute = ApiPublicSubmitAttemptRouteImport.update({
  id: '/api/public/submit-attempt',
  path: '/api/public/submit-attempt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/attempt': typeof AttemptRoute
  '/leaderboard': typeof LeaderboardRoute
  '/result': typeof ResultRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/attempt/$attemptId': typeof AttemptAttemptIdRoute
  '/quiz/offline-check': typeof QuizOfflineCheckRoute
  '/quiz/prepare': typeof QuizPrepareRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/connectivity-check': typeof ApiPublicConnectivityCheckRoute
  '/api/public/submit-attempt': typeof ApiPublicSubmitAttemptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attempt': typeof AttemptRoute
  '/leaderboard': typeof LeaderboardRoute
  '/result': typeof ResultRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/attempt/$attemptId': typeof AttemptAttemptIdRoute
  '/quiz/offline-check': typeof QuizOfflineCheckRoute
  '/quiz/prepare': typeof QuizPrepareRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/connectivity-check': typeof ApiPublicConnectivityCheckRoute
  '/api/public/submit-attempt': typeof ApiPublicSubmitAttemptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/attempt': typeof AttemptRoute
  '/leaderboard': typeof LeaderboardRoute
  '/result': typeof ResultRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/attempt_/$attemptId': typeof AttemptAttemptIdRoute
  '/quiz/offline-check': typeof QuizOfflineCheckRoute
  '/quiz/prepare': typeof QuizPrepareRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/connectivity-check': typeof ApiPublicConnectivityCheckRoute
  '/api/public/submit-attempt': typeof ApiPublicSubmitAttemptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/attempt'
    | '/leaderboard'
    | '/result'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/questions'
    | '/admin/results'
    | '/admin/settings'
    | '/attempt/$attemptId'
    | '/quiz/offline-check'
    | '/quiz/prepare'
    | '/admin/'
    | '/api/public/connectivity-check'
    | '/api/public/submit-attempt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attempt'
    | '/leaderboard'
    | '/result'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/questions'
    | '/admin/results'
    | '/admin/settings'
    | '/attempt/$attemptId'
    | '/quiz/offline-check'
    | '/quiz/prepare'
    | '/admin'
    | '/api/public/connectivity-check'
    | '/api/public/submit-attempt'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/attempt'
    | '/leaderboard'
    | '/result'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/questions'
    | '/admin/results'
    | '/admin/settings'
    | '/attempt_/$attemptId'
    | '/quiz/offline-check'
    | '/quiz/prepare'
    | '/admin/'
    | '/api/public/connectivity-check'
    | '/api/public/submit-attempt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AttemptRoute: typeof AttemptRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ResultRoute: typeof ResultRoute
  AttemptAttemptIdRoute: typeof AttemptAttemptIdRoute
  QuizOfflineCheckRoute: typeof QuizOfflineCheckRoute
  QuizPrepareRoute: typeof QuizPrepareRoute
  ApiPublicConnectivityCheckRoute: typeof ApiPublicConnectivityCheckRoute
  ApiPublicSubmitAttemptRoute: typeof ApiPublicSubmitAttemptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempt': {
      id: '/attempt'
      path: '/attempt'
      fullPath: '/attempt'
      preLoaderRoute: typeof AttemptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/attempt_/$attemptId': {
      id: '/attempt_/$attemptId'
      path: '/attempt/$attemptId'
      fullPath: '/attempt/$attemptId'
      preLoaderRoute: typeof AttemptAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/offline-check': {
      id: '/quiz/offline-check'
      path: '/quiz/offline-check'
      fullPath: '/quiz/offline-check'
      preLoaderRoute: typeof QuizOfflineCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/prepare': {
      id: '/quiz/prepare'
      path: '/quiz/prepare'
      fullPath: '/quiz/prepare'
      preLoaderRoute: typeof QuizPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connectivity-check': {
      id: '/api/public/connectivity-check'
      path: '/api/public/connectivity-check'
      fullPath: '/api/public/connectivity-check'
      preLoaderRoute: typeof ApiPublicConnectivityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submit-attempt': {
      id: '/api/public/submit-attempt'
      path: '/api/public/submit-attempt'
      fullPath: '/api/public/submit-attempt'
      preLoaderRoute: typeof ApiPublicSubmitAttemptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCreateRoute: typeof AdminCreateRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreateRoute: AdminCreateRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AttemptRoute: AttemptRoute,
  LeaderboardRoute: LeaderboardRoute,
  ResultRoute: ResultRoute,
  AttemptAttemptIdRoute: AttemptAttemptIdRoute,
  QuizOfflineCheckRoute: QuizOfflineCheckRoute,
  QuizPrepareRoute: QuizPrepareRoute,
  ApiPublicConnectivityCheckRoute: ApiPublicConnectivityCheckRoute,
  ApiPublicSubmitAttemptRoute: ApiPublicSubmitAttemptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
